; ============================================================================
; Conquer Kayank - Client Configuration
; ============================================================================

[Display]
; Resolução da Janela (O padrão antigo era 800x600 ou 1024x768)
Width=1024
Height=768
; 0 = Modo Janela, 1 = Tela Cheia (Fullscreen)
Fullscreen=1
; 0 = Desativado, 1 = Ativado (Sincronização Vertical)
VSync=1
; Limite máximo de quadros por segundo (0 = ilimitado)
FPSLimit=999

[Network]
; IP do seu Emulador Local (ex: 127.0.0.1) ou do Servidor Dedicado
AuthServerIP=127.0.0.1
; Porta padrão de Login do Conquer Online
AuthServerPort=9958
; Porta padrão do Servidor de Jogo
GameServerPort=5816

[Audio]
; Controle de Volumes (0 a 100)
MasterVolume=100
MusicVolume=50
SoundVolume=80
; 0 = Mudo, 1 = Tocar Áudio
Enabled=1

[Game]
; Define o idioma dos textos carregados (se for implementar multi-linguagem futuramente)
Language=enUS
; 1 = Mostra o Console preto com logs e FPS na tela. 0 = Esconde.
DebugMode=1
; Ignora a tela de abertura da TQ Digital e vai direto pro Login
SkipIntro=1

[Client]
; Aqui o jogo salvará automaticamente a pasta do cliente que você selecionou naquela janela
ClientPath=D:\\projetos\\kayank\\5017\\cliente